spring:
  cloud:
    config:
      uri: http://localhost:7011
      profile: dev
      label: master
    consul:
      host: 192.168.74.133
      port: 8500
      discovery:
        register: false
  application:
    name: dragonAuth
server:
  port: 7012