spring:
  cloud:
    config:
      server:
        git:
          uri: file:///G:/IDEAWorkSpace/dragon-master
          search-paths: /DragonConfig
    consul:
      host: 192.168.74.133
      port: 8500
      discovery:
        register: false
  application:
    name: dragonConfig
server:
  port: 7011